### ISSUE TITLE
Rejoindre une partie

### ISSUE THREAD

**Issue by CalmettesT** [Machurui/ProjetE4-React#2]
En tant qu'utilisateur 
Je veux rejoindre une partie SCRUM 
En utilisant le code unique

**Comment by Machurui** [comment]
- Affichage des champs (Code de la partie, pseudonyme de l'utilisateur, choix du ou des rôle(s))
- Affichage du bouton "Rejoindre"
- Redirection après validation sur la page de gestion de la partie
- Affichage du code de la partie
